version: '3'
services:
  user-ms:
    build: './'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - /user-ms/ms
    ports:
      - '5000:3000'
    depends_on:
      - user-db
    environment:
      - POSTGRES_HOST=user-db
  user-db:
    image: postgres
    volumes:
      - /user-ms/db
    ports:
      - '5001:5432'